#!/usr/bin/env bash
#
# docker-credential-helper for environment variables
#
# DESCRIPTION
# Provides credentials for a server URL taken from environment variables.
#
# USAGE
# Set the following environment variables:
# * Server URL: `$DC_ENV_HOST`
# * Username:   `$DC_ENV_USER`
# * Password    `$DC_ENV_PASSWORD`
#
# When these are not set, the following
# [predefined variables](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html)
# of [GitLab CI](https://docs.gitlab.com/ee/ci/) are used as fallback:
# * Server URL: `$CI_REGISTRY`
# * Username:   `$CI_REGISTRY_USER`
# * Password    `$CI_REGISTRY_PASSWORD`
#
# This code is heavily inspired by the [initial implementation](https://gist.github.com/jasonk/480d87b49e4c8caf51932f184ff764b2)
# of Jason Kohles.
#
set -eu

log() {
  >&2 echo "${@}"
  echo "${@}"
}

cancel() {
  log "${@}"
  return 1
}

prepare_variables() {
  [ -n "${DC_ENV_HOST-}"     ] || [ -z "${CI_REGISTRY-}"          ] || DC_ENV_HOST="${CI_REGISTRY}"
  [ -n "${DC_ENV_USER-}"     ] || [ -z "${CI_REGISTRY_USER-}"     ] || DC_ENV_USER="${CI_REGISTRY_USER}"
  [ -n "${DC_ENV_PASSWORD-}" ] || [ -z "${CI_REGISTRY_PASSWORD-}" ] || DC_ENV_PASSWORD="${CI_REGISTRY_PASSWORD}"
  if [ -z "${DC_ENV_HOST-}" ] || [ -z "${DC_ENV_USER-}" ] || [ -z "${DC_ENV_PASSWORD-}" ]; then
    cancel "One or more environment variables is missing: [DC_ENV_HOST, DC_ENV_USER, DC_ENV_PASSWORD]";
  fi
  DC_ENV_HOST="${DC_ENV_HOST#https://}"
  DC_ENV_HOST="${DC_ENV_HOST%%/*}"
}

main() {
  case "${1-}" in
    get) read -r requested_host
         [ "${requested_host}" = "${DC_ENV_HOST}" ] || cancel "No credentials available for server URL '${requested_host}'."
         printf '{"ServerURL":"%s","Username":"%q","Secret":"%q"}\n' \
                "${DC_ENV_HOST}" "${DC_ENV_USER}" "${DC_ENV_PASSWORD}"
         ;;
    store|erase|list) log "Ignoring unimplemented command '${1}'." ;;
    *) cancel "Unsupported command: ${1:-<none>}" ;;
  esac
}

[ -n "${1-}" ] || cancel "Syntax: ${0} get"
prepare_variables
main "${@}"
