#!/usr/bin/env bash
set -eua
here="$(dirname "${0}")"

repo_owner="${REPO_OWNER:-owner}"
repo_name="${repo_owner}/$(basename $(realpath "${here}"))"
DOCKER_REPO="${DOCKER_REPO:-index.docker.io/${repo_name}}"
DOCKER_TAG="${DOCKER_TAG:-latest}"
DOCKERFILE_PATH="${DOCKERFILE_PATH:-Dockerfile}"
IMAGE_NAME="${IMAGE_NAME:-${DOCKER_REPO}:${DOCKER_TAG}}"
SOURCE_REPOSITORY_URL="${SOURCE_REPOSITORY_URL:-https://github.com/${repo_name}}"
SOURCE_BRANCH="${SOURCE_BRANCH:-$(2>/dev/null git rev-parse --abbrev-ref HEAD || true)}"
SOURCE_COMMIT="${SOURCE_COMMIT:-$(2>/dev/null git rev-parse --short HEAD || true)}"
COMMIT_MSG="${COMMIT_MSG:-Commit message}"

pushd "$(dirname "${here}")/image"

hooks="./hooks"
for hook in post_checkout pre_build build post_build pre_test test post_test pre_push push post_push; do
  file="${hooks}/${hook}"
  if [ -x "${file}" ]; then
    . "${file}"
  else
    >&2 echo "Ignoring missing hook ${hook}"
  fi
done

popd
