variables:
  BUILD_CONTEXT:      image
  IMAGE_PLATFORMS:    linux/amd64,linux/arm/v7

include:
  remote: "https://github.com/git-developer/docker-support/raw/v2.0.0/gitlab-ci/docker-support.yml"

stages:
  - prepare
  - publish

Collect Tags:
  extends: .docker_support:.collect_tags
  stage: prepare

Collect Labels:
  extends: .docker_support:.collect_labels
  stage: prepare

Build Image:
  extends: .docker_support:.build_bare_image
  stage: prepare

Publish Image:
  extends: .docker_support:.publish_image
  stage: publish
